=== AlesandroQuiros/2023-Project-2-Website/dtd/store_DTD.dtd
<!-- Store -->
<!ELEMENT store (name,business,personel,sellers,vat,storage,services)>
<!ELEMENT name (#PCDATA)>
<!-- Business Data -->
<!ELEMENT business (name,location)>
<!-- Business Location -->
<!ELEMENT location (street,postcode,city,province,country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT province (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!-- Personel -->
<!ELEMENT personel (roles+,management+,staff+)>
<!-- Roles -->
<!ELEMENT roles (role+)>
<!ELEMENT role (name)>
<!ATTLIST role id (CEO|CS|WD) #REQUIRED>
<!-- Management -->
<!ELEMENT management (employee+)>
<!ELEMENT employee (name,age,position,infractions?)>
<!ATTLIST employee id ID #REQUIRED>
<!ELEMENT age (#PCDATA)>
<!ELEMENT position EMPTY>
<!ATTLIST position role (CEO|CS|WD) #REQUIRED>
<!-- Staff -->
<!ELEMENT staff (employee+)>
<!ELEMENT infractions (#PCDATA)>
<!-- Sellers/Companies -->
<!ELEMENT sellers (company+)>
<!ELEMENT company (name,web)>
<!ATTLIST company id NMTOKEN #REQUIRED>
<!ELEMENT web (#PCDATA)>
<!-- iva -->
<!ELEMENT vat (#PCDATA)>
<!-- Storage -->
<!ELEMENT storage (product+)>
<!-- Product -->
<!ELEMENT product (name,price,image)>
<!ATTLIST product id ID #REQUIRED>
<!ATTLIST product company NMTOKEN #REQUIRED>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency (euro|dollar) #REQUIRED>
<!ELEMENT image (#PCDATA)>
<!-- Services -->
<!ELEMENT services (service+)>
<!-- Service -->
<!ELEMENT service (name,price,image)>
<!ATTLIST service id ID #REQUIRED>

=== AlesandroQuiros/2023-Project-2-Website/xml/store.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE store SYSTEM "../dtd/store_DTD.dtd">
<?xml-model href="../xsd/store_XSD.xsd"?>
<store>
    <name>WebsiteName</name>
    <business>
        <name>BusinessName</name>
        <location>
            <street>12 Street</street>
            <postcode>01009</postcode>
            <city>Vitoria-Gasteiz</city>
            <province>√Ålava</province>
            <country>Spain</country>
        </location>
    </business>
    <personel>
        <roles>
            <role id="CEO">
                <name>Chief Executive Officer</name>
            </role>
            <role id="CS">
                <name>Customer Support</name>
            </role>
            <role id="WD">
                <name>Web Developer</name>
            </role>
        </roles>
        <management>
            <employee id="CM-001">
                <name>Urtzi</name>
                <age>18</age>
                <position role="CEO" />
            </employee>
            <employee id="CM-002">
                <name>Alesandro</name>
                <age>18</age>
                <position role="CEO" />
            </employee>
        </management>
        <staff>
            <employee id="CS-010">
                <name>a</name>
                <age>21</age>
                <position role="CS" />
                <infractions>0</infractions>
            </employee>
            <employee id="CS-011">
                <name>c</name>
                <age>23</age>
                <position role="CS" />
                <infractions>1</infractions>
            </employee>
            <employee id="WD-266">
                <name>hs</name>
                <age>66</age>
                <position role="WD" />
                <infractions>2</infractions>
            </employee>
        </staff>
    </personel>
    <sellers>
        <company id="PRI">
            <name>Pride</name>
            <web>https://pride.com</web>
        </company>
        <company id="EQU">
            <name>Equality</name>
            <web>https://equality.com</web>
        </company>
    </sellers>
    <vat>15</vat>
    <storage>
        <product id="PF-1002" company="PRI">
            <name>Pride Flag</name>
            <price currency="euro">9.99</price>
            <description>Express your pride with this bright pride flag!</description>
            <description>Size: 75x200cm</description>
            <image>Pride_Flag.png</image>
        </product>
        <product id="BF-1003" company="EQU">
            <name>Bisexual Flag</name>
            <price currency="dollar">9.89</price>
            <description>Express your pride in being bisexual with this colourful bisexual flag!</description>
            <description>Comes in 2 sizes: 35x100cm and 75x200cm</description>
            <image>Bisexual_Flag.png</image>
        </product>
        <product id="PF-1004" company="PRI">
            <name>Transgender Flag</name>
            <price currency="euro">12.99</price>
            <description>Show off your pride on being transgender with this beautiful transgender flag!</description>
            <description>Size: 75x200cm</description>
            <image>Transgender_Flag.png</image>
        </product>
    </storage>
    <services>
        <service id="AA-3667">
            <name>jdasjhk</name>
            <price currency="euro">788</price>
            <description>A</description>
            <image>jhgfdsgh</image>
        </service>
        <service id="OC-8278">
            <name>oo</name>
            <price currency="dollar">688</price>
            <description>A</description>
            <image>hh</image>
        </service>
        <service id="XO-2578">
            <name>pasljd</name>
            <price currency="euro">120</price>
            <description>A</description>
            <description>b</description>
            <image>diamante1.jpg</image>
        </service>
    </services>
</store>

=== AlesandroQuiros/2023-Project-2-Website/xml/store_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE store SYSTEM "../dtd/store_DTD.dtd">
<?xml-model href="../xsd/store_XSD.xsd"?>
<store>
    <name>WebsiteName</name>
    <business>
        <name>BusinessName</name>
        <location>
            <street>12 Street</street>
            <postcode>01009</postcode>
            <city>Vitoria-Gasteiz</city>
            <province>√Ålava</province>
            <country>Spain</country>
        </location>
    </business>
    <personel>
        <roles>
            <role id="CEO">
                <name>Chief Executive Officer</name>
            </role>
            <role id="CS">
                <name>Customer Support</name>
            </role>
        </roles>
        <management>
            <employee id="CM-001">
                <name>Urtzi</name>
                <age>19</age>
                <position role="CEO" />
            </employee>
            <employee id="CM-002">
                <name>Alesandro</name>
                <age>18</age>
                <position role="CEO" />
            </employee>
        </management>
        <staff>
            <employee id="CS-010">
                <name>a</name>
                <age>21</age>
                <position role="CS" />
                <infractions>0</infractions>
            </employee>
            <employee id="CS-011">
                <name>c</name>
                <age>23</age>
                <position role="CS" />
                <infractions>1</infractions>
            </employee>
        </staff>
    </personel>
    <sellers>
        <company id="ORA">
            <name>and</name>
            <web>https://yes.com</web>
        </company>
        <company id="AND">
            <name>or</name>
            <web>https://aaaaa.com</web>
        </company>
    </sellers>
    <vat>15</vat>
    <storage>
        <product id="AC-2562" company="ORA">
            <name>And</name>
            <price currency="euro">5.99</price>
            <image>h</image>
        </product>
        <product id="OC-7278" company="AND">
            <name>oo</name>
            <price currency="dollar">688</price>
            <image>hh</image>
        </product>
        <product id="XO-7567" company="XOR">
            <name>Xor</name>
            <price currency="euro">5.99</price>
            <image>h</image>
        </product>
    </storage>
    <services>
        <service id="AA-3667">
            <name>jdasjhk</name>
            <price currency="euro">788</price>
            <image>jhgfdsgh</image>
        </service>
        <service id="OC-8278">
            <name>oo</name>
            <price currency="dollar">688</price>
            <image>hh</image>
        </service>
        <service id="XO-2578">
            <name>pasljd</name>
            <price currency="euro">120</price>
            <image>yy</image>
        </service>
    </services>
</store>
